In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import cv2
%matplotlib inline
from matplotlib import pyplot as plt
import os
from torchvision.models import resnet50, ResNet50_Weights
from torch.utils.data import Dataset, DataLoader
from torchvision.io import read_image
import torch
import torch.nn as nn

In [103]:
def get_window(img, x, y, window_size = 16):

    x_min = x - window_size//2
    x_max = x + window_size//2

    y_min = y - window_size//2
    y_max = y + window_size//2

    return img[y_min : y_max, x_min : x_max, :]

In [6]:
class OCTImgs(Dataset):
    
    def __init__(self, transform=ResNet50_Weights.DEFAULT.transforms()):
        """
        ...
        """
        self.data_dir = os.path.join('../../model_imgs')

        self.data = os.listdir(self.data_dir)
            
        self.transform = transform

    def __len__(self):

        return len(self.data)

    def __getitem__(self, idx):
        
        curr_dir = os.path.join(self.data_dir, self.data[idx])
        imgs = [self.transform(read_image(os.path.join(curr_dir, img))) for img in os.listdir(curr_dir)]

        return torch.FloatTensor(np.stack(imgs, axis=0).astype(np.float32))

dataloader = DataLoader(OCTImgs(), batch_size=1, shuffle=True)

In [34]:
from utils.tokenizer import VideoTokenizer

vtok = VideoTokenizer()
vtok.sequence_length()

3

In [8]:
from src.cct import CCT

model = CCT()

In [24]:
# for _, d in enumerate(dataloader, 0):
#     x, y = d
#     print(model(x))

In [3]:
from utils.data import OCTVideos

dataloader = DataLoader(OCTVideos(), batch_size=2, shuffle=True)

In [4]:
from cct import CCT

model = CCT()

In [6]:
for _, d in enumerate(dataloader, 0):
    x, y = d
    print(model(x))

tensor([[0.3331, 0.2753],
        [0.2709, 0.4318]], grad_fn=<AddmmBackward0>)
tensor([[0.2842, 0.2735],
        [0.1517, 0.4286]], grad_fn=<AddmmBackward0>)
tensor([[0.3097, 0.0224],
        [0.3083, 0.2844]], grad_fn=<AddmmBackward0>)
tensor([[0.2157, 0.2163],
        [0.3155, 0.2908]], grad_fn=<AddmmBackward0>)
tensor([[0.3523, 0.2894],
        [0.3186, 0.2844]], grad_fn=<AddmmBackward0>)


KeyboardInterrupt: 